spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

file:
  path: D:\Code\JavaProjects\SpringBoot-Projects\spring-boot-demos\spring-boot-upload\src\main\resources\